export { default as Layout } from './Layout/Layout'
export { default as CustomButton } from './Button/Custom_Button'
export { default as YoutubeEmbed } from './YoutubeEmbed/YoutubeEmbed'
export { default as RegisterPage } from './RegisterPage/register'
export { default as MainPage } from './MainPage/MainPage'
export { default as Notification } from './Notification/Notification'